name = "pinning-api"
main = "dist/index.js"
compatibility_date = "2025-11-11"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "pinning-api"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "pinning.centrifuge.io", custom_domain = true }
]
# Secrets should be set using: wrangler secret put <SECRET_NAME>
# Required secrets:
# - PINATA_JWT

